# Generated by Django 5.2 on 2025-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('premium', 'Premium'), ('premium_pro', 'Premium Pro')], default='free', max_length=20, verbose_name='Abonelik Seviyesi'),
        ),
    ]
