# Generated by Django 5.2 on 2025-12-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_subscription_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('workshop', 'Dükkân Sahibi'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Rol'),
        ),
    ]
