# Generated by Django 4.2.20 on 2025-11-23 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Yanıt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review', verbose_name='Yorum')),
            ],
            options={
                'verbose_name': 'Yorum Yanıtı',
                'verbose_name_plural': 'Yorum Yanıtları',
            },
        ),
    ]
