# Generated by Django 5.2 on 2025-12-14 00:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('workshops', '0002_remove_workshop_latitude_remove_workshop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Alış'), ('sale', 'Satış'), ('return', 'İade'), ('adjustment', 'Manuel Düzeltme')], max_length=20, verbose_name='Hareket Türü'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Parça Adı (Usta Dili)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marka (OEM/Muadil/Üretici)')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Parça Kodu (Opsiyonel)')),
                ('auto_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Otomatik Kod')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Görsel')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok Miktarı')),
                ('min_stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Stok')),
                ('current_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Güncel Alış Fiyatı')),
                ('current_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Güncel Satış Fiyatı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshops.workshop', verbose_name='Dükkân')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlternativePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for', to='inventory.part', verbose_name='Alternatif Parça')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='inventory.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Alternatif Parça',
                'verbose_name_plural': 'Alternatif Parçalar',
                'unique_together': {('part', 'alternative')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.part', verbose_name='Parça'),
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Alt Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Parça Kategorisi',
                'verbose_name_plural': 'Parça Kategorileri',
                'ordering': ['name', 'subcategory'],
                'unique_together': {('name', 'subcategory')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='inventory.partcategory', verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='PartNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_notes', to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Parça Notu',
                'verbose_name_plural': 'Parça Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış Fiyatı')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miktar')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Tedarikçi')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='inventory.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Alış Fiyatı',
                'verbose_name_plural': 'Alış Fiyatları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miktar')),
                ('customer', models.CharField(blank=True, max_length=200, verbose_name='Müşteri')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_prices', to='inventory.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Satış Fiyatı',
                'verbose_name_plural': 'Satış Fiyatları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year_from', models.IntegerField(verbose_name='Başlangıç Yılı')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Motor')),
                ('engine_code', models.CharField(blank=True, max_length=50, verbose_name='Motor Kodu')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'ordering': ['brand', 'model', 'year_from'],
                'unique_together': {('brand', 'model', 'year_from', 'year_to', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='inventory.part', verbose_name='Parça')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_parts', to='inventory.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Parça Uyumluluğu',
                'verbose_name_plural': 'Parça Uyumlulukları',
                'ordering': ['vehicle__brand', 'vehicle__model'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='inventory_p_name_c0a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['code'], name='inventory_p_code_78998b_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['auto_code'], name='inventory_p_auto_co_48a661_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partcompatibility',
            unique_together={('part', 'vehicle')},
        ),
    ]
