# Generated by Django 5.2 on 2025-12-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stockmovement_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.part', verbose_name='Parça'),
            preserve_default=False,
        ),
    ]
