# Generated by Django 4.2.20 on 2025-11-23 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dükkân Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Enlem')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Boylam')),
                ('city', models.CharField(default='Adıyaman', max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Mahalle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='Resim')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Ortalama Puan')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Toplam Yorum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Premium Tarihi')),
                ('is_closed_today', models.BooleanField(default=False, verbose_name='Bugün Kapalı')),
                ('closed_today_reason', models.CharField(blank=True, max_length=200, verbose_name='Kapalı Olma Sebebi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.category', verbose_name='Kategori')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Dükkân',
                'verbose_name_plural': 'Dükkanlar',
                'ordering': ['-is_premium', '-average_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshops.workshop', verbose_name='Dükkân')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('opening_time', models.TimeField(verbose_name='Açılış Saati')),
                ('closing_time', models.TimeField(verbose_name='Kapanış Saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Kapalı')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='workshops.workshop', verbose_name='Dükkân')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'ordering': ['day_of_week'],
                'unique_together': {('workshop', 'day_of_week')},
            },
        ),
    ]
