# Generated by Django 5.2 on 2025-12-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='longitude',
        ),
    ]
