# Generated by Django 5.2 on 2025-12-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_latitude_remove_workshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam'),
        ),
    ]
