# Generated by Django 4.2.20 on 2025-11-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Fatura Numarası')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('status', models.CharField(choices=[('paid', 'Ödendi'), ('pending', 'Beklemede'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Düzenlenme Tarihi')),
                ('due_date', models.DateTimeField(verbose_name='Son Ödeme Tarihi')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Süre (Gün)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('features', models.TextField(blank=True, verbose_name='Özellikler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Premium Plan',
                'verbose_name_plural': 'Premium Planlar',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Ödeme Yöntemi')),
                ('transaction_id', models.CharField(blank=True, max_length=200, unique=True, verbose_name='İşlem ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.premiumplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
                'ordering': ['-start_date'],
            },
        ),
    ]
