# Generated by Django 5.2 on 2025-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='level',
            field=models.CharField(choices=[('premium', 'Premium'), ('premium_pro', 'Premium Pro')], default='premium', max_length=20, verbose_name='Seviye'),
        ),
    ]
